# =========================
# Account Service – DEV
# =========================

spring:
  datasource:
    url: jdbc:mysql://account-mysql-dev:3306/accountsdb
    username: mr.mime
    password: StudyBuddy*123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

    info:
      env:
        enabled: true

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
