logging:
  level:
    root: INFO
    com.studybuddy: DEBUG
    org.springframework.jdbc.core: DEBUG # Show SQL logs

spring:
  rabbitmq:
    host: rabbitmq-dev
    port: 5672
    username: guest
    password: guest

testing:
  profile:
    name: dev


