# =========================
# Collaboration Service – DEV
# =========================

spring:
  datasource:
    url: jdbc:mysql://collaboration-mysql-dev:3306/collaboration_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: mr.mime
    password: StudyBuddy*123
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    repair: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

    info:
      env:
        enabled: true

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

testing:
  profile:
    name: dev
