logging:
  level:
    root: INFO
    com.studybuddy: DEBUG
    org.springframework.jdbc.core: DEBUG # Show SQL logs

spring:
  rabbitmq:
    host: rabbitmq-dev
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://collaboration-mysql-dev:3306/collaboration_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: mr.mime
    password: StudyBuddy*123
    driver-class-name: com.mysql.cj.jdbc.Driver

testing:
  profile:
    name: dev


