# =========================
# Collaboration Service – PROD
# =========================

spring:
  datasource:
    url: jdbc:mysql://collaboration-mysql-prod:3306/collaboration_service?useSSL=true&serverTimezone=UTC
    username: mr.mime
    password: ${COLLAB_DB_PASSWORD}   # injected securely
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  rabbitmq:
    host: rabbitmq-prod
    port: 5672
    username: guest
    password: guest

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    repair: false   # NEVER auto-repair in prod

logging:
  level:
    root: WARN
    com.studybuddy: INFO
    org.springframework.jdbc.core: WARN

management:
  endpoint:
    health:
      show-details: never

testing:
  profile:
    name: prod