# =========================
# Gateway Server – DEV
# =========================

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service
              uri: http://account-service-dev:8081
              predicates:
                - Path=/studybuddy/account/**
              filters:
                - RewritePath=/studybuddy/account/(?<segment>.*), /${segment}

            - id: collaboration-service
              uri: http://collaboration-service-dev:8082
              predicates:
                - Path=/studybuddy/collab/**
              filters:
                - RewritePath=/studybuddy/collab/(?<segment>.*), /${segment}

        httpclient:
          connect-timeout: 1000
          response-timeout: 10s

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

    info:
      env:
        enabled: true

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
